services:
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=database
    depends_on:
      - database
  database:
    build: .
    restart: unless-stopped
    ports:
      - "3306:3306"